In [ ]:
import numpy as np
def greedy(A):
    M=A
    Mrows=M.shape[0]
    L=np.identity(Mrows)
    while L.shape[1]>A.shape[1]:
        rowvals=np.zeros(M.shape[0])
        mergevals=np.zeros((M.shape[0],M.shape[0]))
        for i in range(M.shape[0]):
            rowvals[i]=M[i][M[i] > 0].sum()

        for i in range(M.shape[0]):
            for j in range(M.shape[0]):
                s = M[i] + M[j] 
                pos_sum = s[s > 0].sum()
                mergevals[i, j] = pos_sum - rowvals[i] - rowvals[j]

        ropt=np.argmin(rowvals)
        iopt=np.argmin(mergevals[0])
        jopt=np.argmin(mergevals[1])

        if mergevals[iopt,jopt]>rowvals[ropt]:
            M[iopt]=M[iopt]+M[jopt]
            M=np.delete(M,jopt,axis=0)
            L[:,iopt]=L[:,iopt]+ L[:,jopt]
            L=np.delete(L,jopt,axis=1)
        else:
            M=np.delete(M,ropt,axis=0)
            L=np.delete(L,ropt,axis=1)
    


    return L 


print(greedy(np.array([[1000, 2, 3], [4, 5000000, 6], [7, 849863, 9], [10, 11, 12],[233, 45, 3], [34, 12, 5]])))




[[   1000       2       3]
 [      4 5000000       6]
 [      7  849863       9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
